[package]
name = "flex"
version = "0.1.0"
edition = "2023_01"

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.14.0" }
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.8.0"  }
starknet = "2.4.3"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true
